### ISSUE TITLE
liftovervcf does not change genotypes when allele swap happens between two reference builds

### ISSUE THREAD

**Issue by chenwenan** [broadinstitute/picard#1040]
### Affected tool(s)
picard 

### Affected version(s)
2.15.0, 2.17.0
I tried to test 2.17.0 and also got errors for indels such as:

Exception in thread "main" java.lang.IllegalArgumentException: Reference allele doesn't match reference: Allele= TGT*, at chr10:51637172-51637174, ref=ttt

### Description 
When there are reference alleles switch between two reference builds, the genotypes should reflect this change. For example, 0/0 will be 1/1. 
A work around is to simply reject these variants to avoiding editing the genotypes.

#### Steps to reproduce
Here are some examples liftover GRCh38 to GRCh37
I used two steps liftover. 
The chaine files: hg38ToHg19.over.chain.gz and then hg19ToGRCh37.over.chain.gz
The reference files are from gatk bundle: ucsc.hg19.fasta and human_g1k_v37.fasta

chr10_45968302_G_C: 10 51627538 C G
chr12_80455318_C_G: 12 80854858 G C

#### Expected behavior
Either reject these variants or change the genotypes

#### Actual behavior
These variants are lifted over without changing the genotypes

**Comment by yfarjoun** [comment]
I think that this works for SNPs and fails for (rev-comp'ed) indels.
There's currently a PR in review that will reject the indels in case of
reference changes.

**Comment by chenwenan** [comment]
Thanks for your quick reply. 
For SNPs, it can identify the allele swap. However, the genotypes stay the same, which results that the genotypes are wrong after liftover.

**Comment by yfarjoun** [comment]
could you please double-check that you're using the latest version? in particular the last two versions should contain this PR: #971 which is intended to address your issue explicitly.

**Comment by chenwenan** [comment]
I did the check with 2.17.0

Here is the input vcf in hg38:
chr12   80455318        chr12_80455318_C_G      C       G ... 0/0

Here is the output vcf in hg19:
chr12   80854858        chr12_80455318_C_G      G       C ... **0/0**

The problem is that the genotype should be 1/1 after the allele switch.
A quick fix would simply reject this kind of allele swap, so to avoid writing code to fix the genotypes.

**Comment by yfarjoun** [comment]
Hi @chenwenan, I have a PR #1050 that seems to show that genotypes are really lifted over correctly.

Looking more carefully at your example, I think that you might be confused about the reason why your alleles have changed. It seems to me that in reality, they aren't swapped. Instead, what's going on is that the liftover block to which your variant belongs is reverse aligned. This means that the alleles need to be (reverse) complemented before being turned into a variant...this changes the G to a C and vice versa, but not due to swapping. It's confusing. 

If it were due to swapping you'd have a INFO field annotation "SwappedAlleles". One way to test this hypothesis is to create a tiny vcf with just one variant, and change the ALT allele from a G to a T. I predict the output VCF will have C/A not T/G (nor will the variant be rejected due to mismatching reference). As I said, another way to test this would be to look for the "SwappedAlleles" INFO field annotation.

**Comment by andrew-slater** [comment]
@yfarjoun , when you say there is a PR in review that will reject the indels in case of reference changes, do you mean this will fix the "Reference allele doesn't match reference" error @chenwenan reported by writing such records to the REJECT file instead of exiting? Do you have an estimated timeline for merging that or a recommended workaround for lifting VCF files which contain such indels?

**Comment by chenwenan** [comment]
Hi, @yfarjoun, Thank you for pointing out that. I think you are right, they are not allele swaps. So no genotype modification is needed. 

Here comes another question that I am not sure. If there exists an allele swap, will picard do the genotype modification in the code implementation? e.g., 0/0 -> 1/1

@andrew-slater, reporting to the reject file would be nice. Otherwise we either need to use the older version, e.g., 2.15.0, or manually remove those that causes the exit problem.

Thank you

**Comment by yfarjoun** [comment]
I think that everything is lifting over correctly at things point. Please
look at my pr. It shows two examples of lift over with rejected variants.

**Comment by yfarjoun** [comment]
@andrew-slater I think that this is the current behavior of liftover...please let me know if not.

**Comment by yfarjoun** [comment]
@chenwenan Yes: GT, AD, PL will be modified correctly, also AF and other AF-like INFO fields, if you list them on the commandline.
