### ISSUE TITLE
Error in installation. ***Build Failed***

### ISSUE THREAD

**Issue by shreyashruti** [broadinstitute/picard#1056]
I ran 

> ./gradlew shadowJar

Error I am getting is:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/syslogin/picard/build.gradle' line: 55

* What went wrong:
A problem occurred evaluating root project 'picard'.
> Cannot invoke method getURLs() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
What do I do now?

**Comment by merceneryinbox** [comment]
Hello, I faced with the same  and in my case following helped:  
It can be solved by correctly setting global environment variables -  java and gradle inside the operating system. 
 Add the installation path of the java machine and gradle to /etc/environment insert /usr/lib/jvm/default-java before " symbol and after : symbol in the same string 
(path is valid in my case, but you need to ensure where is your java machine is, for less movements you may use: sudo apt-get install default-jdk      
and than your path will be /usr/lib/jvm/default-jdk).
 You need to insert at the string after last one in /etc/profile next strings(instead of my paths you have to insert yours): 
JAVA_HOME=/usr/lib/jvm/default-java     
GRADLE_HOME=/opt/gradle/gradle-4,1 
PATH=$PATH:$HOME/bin:$JAVA_HOME/bin:$GRADLE_HOME/bin 
     It is also necessary to check the default using system variables if several versions of java and gradle have been installed: 
update-alternatives --install
and 
update-alternatives --config 
(reference to video example instructions for the command line settings on debian OS https://www.youtube.com/watch?v=xfD3DSfktnA)
