### ISSUE TITLE
Problem running ./gradlew shadowJar

### ISSUE THREAD

**Issue by thkitapci** [broadinstitute/picard#1089]
I cloned the github and then tried to run ./gradlew shadowJar

it downloads gradlew automatically on my HOME directory but I don't have enough space there (I am running on a computing cluster) I tried to set my env variable HOME to another directory I also tried to modify the picard/gradle/wrapper/gradle-wrapper.properties and set 

GRADLE_USER_HOME=myPATH

but it always downloads to my default HOME. Where does this scripts takes the default "HOME" variable ? How can I change it to a custom path ?

Thanks
Best Regards
Hamdi

**Comment by lbergelson** [comment]
Hi @thkitapci.  

GRADLE_USER_HOME is the full name of the environment variable, if you were setting HOME instead that would explain why it doesn't work I think.

Could you try 
```
export GRADLE_USER_HOME=thePathYouWantToDownloadTo
```
and then try running `./gradlew`

It works for me and downloads to the location I specify.  

Alternatively, you can manually install the correct gradle version (3.1) and invoke the `gradle` command directly instead of using that wrapper, but that's runs the risk of getting out of sync with the version of gradle that picard expects.

**Comment by thkitapci** [comment]
Hi @lbergelson,
I did try to set GRADLE_USER_HOME but I was making a silly bash mistake of setting the variable using 

`GRADLE_USER_HOME=thePathYouWantToDownloadTo`
instead of 

`export GRADLE_USER_HOME=thePathYouWantToDownloadTo`

I just realized that I have to use export so that the variable is available to any sub process

Now it is downloading to the path I want. 

Thanks a lot
Best Regards

**Comment by lbergelson** [comment]
Ah!  I'm glad it was something simple like that!  I've made the same mistake and been confused before.
