### ISSUE TITLE
AT_DROPOUT and GC_DROPOUT question

### ISSUE THREAD

**Issue by wenluo711** [broadinstitute/picard#1106]
### Tool(s) involved
CollectGcBiasMetrics & CollectHSMetrics

### Description 
Both CollectGcBiasMetrics and CollectHSMetrics will generate AT_DROPOUT and GC_DROPOUT. 
I can see from the document that the DROPOUT FROM GcBiasMetrics is about the percentage of misaligned reads that correlate with low (%-GC is < 50%) or high (%-GC is > 50%) GC content respectively. DROPOUT form HSMetrics is about percentage of total reads that should have mapped to GC<=50% regions mapped elsewhere. 
But I'm still not clear about how they are calculated. What does %ref_at_gc and %reads_at_gc mean? How are the GROPOUT from the two metrics different from each other?

Thanks, 
Wen 

----

**Comment by yfarjoun** [comment]
Dropout is the amount of reads that are "missing" relative to some expected value. This expected value is calculated per GC content. if the GC content is <50% the dropout is attributed to AT_DROPOUT, otherwise to GC_DROPOUT. The expected values are calculated from the reference. -

- For GCBias Metrics, the genome is split into "windows" (by default of size 100, parameter SCAN_WINDOW_SIZE) 
- For HSMetrics (and TargetedPCR metrics) the gc content of each target interval is calculated and added to the distribution weighted by the length of the target.

In both cases the algorithem is not counting **misaligned reads** but rather its looking at the aligned reads and trying to figure out the reads that didn't make it (not due to alignment, but more likely due to poor capture or other "conversion" problems)  

I hope this helps!

**Comment by wenluo711** [comment]
I see. Thanks!
Wen

**Comment by lakhujanivijay** [comment]
hi @yfarjoun 

Is there any threshold for AT_DROPOUT and GC_DROPOUT ? Like a bad-range and a good-range ?

**Comment by yfarjoun** [comment]
Please refrain from hijacking the issue. If you have  new question to ask, kindly ask it on the GATK forum https://gatkforums.broadinstitute.org/gatk/categories/gatk-support-forum
