### ISSUE TITLE
IntervalListToBed not documented online

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/picard#1196]
The subcommand `IntervalListToBed` is available in the newest Picard version (2.18.9), but it is not documented here: https://broadinstitute.github.io/picard/command-line-overview.html

**Comment by cmnbroad** [comment]
I suspect the online Picard doc has not been updated in a while (@vdauwera is that correct?) because we only generate doc for the Barclay parser, but thats not the default parser used by Picard. The ultimate solution is to move forward with switching the default parser in Picard (https://github.com/broadinstitute/picard/issues/1120); then we would be able to publish Picard doc again that matches the default parser.

In the meantime, doc for the Picard tools is included in the GATK docs (`IntervalListToBed` for example is [here](https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.0.0/org_broadinstitute_hellbender_tools_walkers_GenotypeGVCFs.php)). @vdauwera would it make any sense to publish a reference to the gatk docs ?

**Comment by yfarjoun** [comment]
correction to link:
https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.0.0/picard_util_BedToIntervalList.php

**Comment by splaisan** [comment]
please point users to a unifies doc instead of 3 different flavours. many examples will just not run and frustrate users because the syntax keeps changing [as I discussed here](https://github.com/broadinstitute/picard/issues/1120#issuecomment-440232957)
