### ISSUE TITLE
[bug] FilterSamReads reformats hexadecimal tags

### ISSUE THREAD

**Issue by RWilton** [broadinstitute/picard#1199]
## Bug Report
FilterSamReads transforms hexadecimal-formatted tags (tag type H) into numeric arrays (tag type B).

### Affected tool(s)
FilterSamReads

### Affected version(s)
- [x] Latest public release version

### Description 
Some examples:
```id:H:00048808008BF9C0``` becomes ```id:B:c,0,4,-120,8,0,-117,-7,-64```
```af:H:F122``` becomes ```af:B:c,-15,34```
```qf:H:0707``` becomes ```qf:B:c,7,7```

#### Steps to reproduce
Execute FilterSamReads with a JAVASCRIPT_FILE that contains a "null" filter (e.g., ```return true;```) and with SAM input that contains tags formatted as _tagname:H:value_, where _value_ conforms to the regex ```([0-9A-F][0-9A-F])*``` in the SAM specification.

#### Expected behavior
Hexadecimal-formatted tags should not be reformatted.

#### Actual behavior
Hexadecimal-formatted tags are transformed into numeric-array-formatted tags.

#### Notes
In theory, the reformatted tags represent the same values, but there is no reason to transform them and several good reasons to leave them alone:
- More compact representation of hexadecimal data.  This is particularly important for the hexadecimal representation of common integer types (2-byte, 4-byte, and 8-byte integers) which are more convenient to read and write in hexadecimal format than as comma-separated lists of signed integers. 
- Software that writes H-formatted tags ought reasonably to expect to read them back in the same format.
- H-formatted tags may be more useful to a human reader.
- Nothing in the SAM specification permits arbitrary changes to the format of optional tags.  (If it did, one might justify the transformation of all such data into base64!)  There is an exception in the case of B-formatted tags, where the array-type specification may change when SAM data is imported or exported, but this is clearly unrelated to the described behavior.

**Comment by lindenb** [comment]
@yfarjoun 

looks like a bug in htsjdk:

```
$ cat ~/jeter.sam
@SQ	SN:ref	LN:45
r001	163	ref	7	30	8M4I4M1D3M	=	37	39	TTAGATAAAGAGGATACTG	*	XX:B:S,12561,2,20,112	af:H:F122
```

```
$ java -jar /picard.jar ViewSam I=jeter.sam 
@SQ	SN:ref	LN:45
r001	163	ref	7	30	8M4I4M1D3M	=	37	39	TTAGATAAAGAGGATACTG	*	XX:B:S,12561,2,20,112	af:B:c,-15,34
```

**Comment by yfarjoun** [comment]
hmmm. reading in the code-base is seems that this change went in circa 2011, in this commit: 125f6854296f2aef62f9bb425c30da4ef1410ec0 . 

I think that this is a question for the maintainers: @jay @lbergelson @tfenne, do we want to allow H-tags to be maintained separately from B-tags?

**Comment by RWilton** [comment]
If I may weigh in on this discussion before it gets too far down the rabbit hole:  A hexadecimal value is *not* a byte array.  Implicit in Picard's transformation from H to B is an assumption about endianness that cannot be inferred from any information available in the SAM format.

Please keep things simple:  H in means H out.

**Comment by tfenne** [comment]
@RWilton I'm not sure if this is your intention, but your last comment comes off quite combative.  Picard (and htsjdk) are open source toolkits that by-and-large are maintained by people who are not compensated for the work in any way.  This is likely not being addressed because it is not a problem for the vast majority of people using the library/tools, and thus those who _could_ fix it are not super-motivated to do so.  I'm unsure if you code or not, but a PR to fix the issues would likely be welcome.

I'm curious why this is causing you problems?  I understand it might be unexpected, and is perhaps not desirable, but where is it becoming a problem?  The two formats (`id:H:....` and `id:B,c,...` are capable of encoding the exact same data (`id:B,c` denoting an array of unsigned bytes).  There's no string or character conversion happening.  The choice in the spec of `c` does perhaps suggest character, but it's defined and implemented as a signed 8bit integer.  Re: `H` tags not being arrays, the definition in the spec is quite literally:
    
> Byte array in the Hex format

with the footnote:

> For example, the six-character Hex string ‘1AE301’ represents the byte array [0x1a, 0xe3, 0x1].

The problem is that HTSJDK does not internally store the fact that the tag was read as `H` or `B,c`, but just stores a byte array internally, and then when it goes to write it encodes it as `B,c` as that's the more efficient encoding in BAM.  Changing this would be quite involved, and is thus unlikely to happen any time soon.

**Comment by RWilton** [comment]
I am sorry -- I was not trying to be "combative" in any way!  And I did not realize that I was running into an edge case here.  I do admit, however, to having been genuinely surprised to discover that a side-effect of filtering a SAM file with a Picard tool was to transform H fields into what at first glance appeared to be gibberish!  Of course, this was a breaking change in a downstream tool that loads SAM records into relational-database tables, since those H fields had an unexpected format after having been re-encoded by Picard.

The underlying problem here is that what the SAM spec *says* is probably not what what the SAM spec *means*.  Is the H representation really intended to represent only binary string entities?  Or is it (as others as well as I have assumed) the same as it is in the rest of the computer-science world, i.e., a hexadecimal representation of a binary value whose size is inferred from the number of hexadecimal characters in the representation (e.g., an integer, a GUID, or a hash value).  In the latter case, an H-formatted value cannot be handled as a string for the reason I've already pointed out.

Anyway, I don't think it's worth pursuing this any further.  Now that I know what to expect, I can always write a B-to-H translator that undoes the damage.

Thanks for taking the time to respond!

**Comment by tfenne** [comment]
@RWilton I'm glad I could help (somewhat?).  I'm still a little confused by what you're saying about Picard treating H as hex-encoded strings.  Either I'm missing something, or you're mistaken.  Picard/htsjdk as best I can tell do in fact treat `H` tags as a series of binary bytes, just as the spec states.  When writing BAM the data is output as a straight binary array of bytes.  Since that won't work in SAM, the data is (rather unfortunately) being converted to a comma-separated list of signed 8-bit numbers representing the bytes parsed from the hex value.  The only assumption here is that the bytes are signed vs. unsigned, but that has nothing to do with strings.

**Comment by RWilton** [comment]
@tfenne Well, I have just learned elsewhere that my conception of the H type in the SAM spec is faulty.  From its history, it seems to have been intended not to represent binary values but rather to encode byte vectors in a somewhat more compact form than the B type.  In any event, I will avoid problems in the future by not using it!
