### ISSUE TITLE
MergeBamAlignment ERROR

### ISSUE THREAD

**Issue by yanglq-bio** [broadinstitute/picard#1308]
Hi,
when I use MergeBamAlignment to merge a unmapped bam and a mapped bam ,I got this error:
INFO    2019-04-11 17:31:14     SamAlignmentMerger      Processing SAM file(s): [N100_pe.tmp.bam]
ERROR   2019-04-11 17:31:14     CigarUtil       143 read length does not = cigar length 148 oldCigar E00548:308:H25F5CCX2:8:1101:10003:20682 1/2 143b aligned to chr9:131100022-131100169. cigar:144M3I4M
ERROR   2019-04-11 17:31:14     CigarUtil       143 read length does not = cigar length 151 oldCigar E00548:308:H25F5CCX2:8:1101:10003:41251 1/2 143b aligned to chr6:131529639-131529789. cigar:151M
ERROR   2019-04-11 17:31:14     CigarUtil       143 read length does not = cigar length 153 oldCigar E00548:308:H25F5CCX2:8:1101:10003:41391 1/2 143b aligned to chr12:62718961-62719113. cigar:145M2D6M
ERROR   2019-04-11 17:31:14     CigarUtil       143 read length does not = cigar length 151 oldCigar E00548:308:H25F5CCX2:8:1101:10044:31582 1/2 143b aligned to chrX:76348728-76348878. cigar:151M

What does it mean? How can I solve it?
my code is:
java -jar gatk MergeBamAlignment \
                -R $ref \
                --UNMAPPED_BAM N100.uBAM \
                --ALIGNED_BAM N100_pe.bam \
                -O N100.merged.bam \
                --CREATE_INDEX true \
                -MAX_GAPS -1 \
                --ALIGNER_PROPER_PAIR_FLAGS true \
                --VALIDATION_STRINGENCY SILENT \
                -SO coordinate \
                -ORIENTATIONS FR \
                --ATTRIBUTES_TO_RETAIN XS

**Comment by yfarjoun** [comment]
This means that you are trying to merge a ubam that has a different readlength from that in the aligned bam. probably due to some clipping that was done on the ubam prior to using merge bam alignment 
It looks like you are missing 8 bases...perhaps you removed a UMI or other type of inline barcode? if that is the caes, you should align the modified ubam and then merge that. 

see, for example: https://software.broadinstitute.org/gatk/documentation/article.php?id=6483

**Comment by elainebblythe** [comment]
but my ubam is already removed UMI. And then ,I used SamToFastq to translate the ubam into fastq file and align to reference genome by bowtie.



elaineylq@163.com
 
From: Yossi Farjoun
Date: 2019-04-11 21:11
To: broadinstitute/picard
CC: elainebblythe; Author
Subject: Re: [broadinstitute/picard] MergeBamAlignment ERROR (#1308)
This means that you are trying to merge a ubam that has a different readlength from that in the aligned bam. probably due to some clipping that was done on the ubam prior to using merge bam alignment
It looks like you are missing 8 bases...perhaps you removed a UMI or other type of inline barcode? if that is the caes, you should align the modified ubam and then merge that.
see, for example: https://software.broadinstitute.org/gatk/documentation/article.php?id=6483

**Comment by yfarjoun** [comment]
I suspect that you are trying to merge the ubam prior to the umi removal (length 151) with the aligned bam that doesn't have the umi (length 143)...since bowtie doesn't change the number of bases in the reads....you need to merge the ubam POST umi removal with the output of bowtie.
