### ISSUE TITLE
Difference between PCT_OFF_BAIT and PCT_EXC_OFF_TARGET

### ISSUE THREAD

**Issue by merckey** [broadinstitute/picard#1419]
Hi,

I'm trying to understand the differences between `PCT_OFF_BAIT ` and `PCT_EXC_OFF_TARGET`.  In one of the sample, these 2 numbers differ a lot.

Field|Value
-- | --
ON_BAIT_BASES | 4308135248
OFF_BAIT_BASES | 16613600849
ON_TARGET_BASES | 2296737480
PF_BASES_ALIGNED | 22057550300
**PCT_OFF_BAIT** | 0.753193
**PCT_EXC_OFF_TARGET** | 0.416608

The `PCT_OFF_BAIT` in the table matches the equation below:
PCT_OFF_BAIT = OFF_BAIT_BASES /  PF_BASES_ALIGNED = 0.7531933

But how to calculate `PCT_EXC_OFF_TARGET`?
I assume it is 1 - ON_TARGET_BASES / PF_BASES_ALIGNED = 0.896, however, the table reports `PCT_EXC_OFF_TARGET` = 0.4166

Could you help me clarify this?
Thanks!
JL

**Comment by yfarjoun** [comment]
well, the base could have been excluded for other reasons....for example, base_quality, low mapping quality, adapter read etc....the PCT_EXC_OFF_TARGET metric tells you the number of bases that did NOT contribute to coverage due to them being off target. it does not mean that all the other bass did contribute to coverage, so the 1-ON_TARGET_BASES / PF_BASES_ALIGNED calculation is incorrect.

**Comment by merckey** [comment]
Thanks for the clarification!
