### ISSUE TITLE
picard fails with hard to understand error message

### ISSUE THREAD

**Issue by 7PintsOfCherryGarcia** [broadinstitute/picard#1591]
### Affected tool(s)
picard MarkDuplicates

### Affected version(s)
2.23.6

### Description 
Program ends complaining about some temporary file. Really hard to understand the cryptic unusable error messages.

#### Steps to reproduce
picard MarkDuplicates REMOVE_DUPLICATES=TRUE INPUT=file.bam OUTPUT=dedup.bam METRICS_FILE=metrics

#### Expected behavior
Should run normally and not complain 

#### Actual behavior
Program finished with your typical uninformative java error: 

    Exception in thread "main" htsjdk.samtools.SAMException:/tmp/CSPI.5010315301700362150.tmp/6881.tmpnot found

[picarderr.txt](https://github.com/broadinstitute/picard/files/5318297/picarderr.txt)

**Comment by pshapiro4broad** [comment]
The error message isn't great, but the underlying problem is in the stack trace: `Too many open files`. If this is a unix based system, there may be system setting or quota that you need to change. Or, you can use the `MAX_FILE_HANDLES_FOR_READ_ENDS_MAP` to limit the files created by `MarkDuplicates. https://gatk.broadinstitute.org/hc/en-us/articles/360036884011-MarkDuplicates-Picard-#--MAX_FILE_HANDLES_FOR_READ_ENDS_MAP

**Comment by 7PintsOfCherryGarcia** [comment]
@pshapiro4broad for the win!!! 

Problem solved :)
