### ISSUE TITLE
AT DROPOUT VALUES

### ISSUE THREAD

**Issue by alessia677** [broadinstitute/picard#1669]
Hi, I ran your CollectGcBiasMetrics:

```
java -jar $PICARDPATH/picard_new.jar  CollectGcBiasMetrics \
      I=sample.bam \
      O=gc_bias_metrics.txt \
      CHART=gc_bias_metrics.pdf \
      S=summary_metrics.txt \
      R=reference
```

And I obtained this results: 

```
ACCUMULATION_LEVEL      READS_USED      WINDOW_SIZE     TOTAL_CLUSTERS  ALIGNED_READS   AT_DROPOUT      GC_DROPOUT      GC_NC_0_19      GC_NC_20_39     GC_NC_40_59     GC_NC_60_79     GC_NC_80_100   SAMPLE  LIBRARY READ_GROUP
All Reads       ALL     100     4523644 9026596 5.563447        0.076132        1.321744        0.844959        0.990274        1.159031        0.879629
```

How do you interpret the AT_DROPOUT value? (5.563447)  Which threshold do you suggest to use ? 

Thank you in advance

**Comment by fleharty** [comment]
You can find a list of picard metrics and what they mean here:
https://broadinstitute.github.io/picard/picard-metric-definitions.html

AT_DROPOUT: Illumina-style AT dropout metric. Calculated by taking each GC bin independently and calculating (%ref_at_gc - %reads_at_gc) and summing all positive values for GC=[0..50].

A single threshold can't be recommended since that will depend a lot on what you are sequencing, and how it is being done.  One way of deciding on an appropriate measure for your data is to collect this metric for a number of samples you believe are performing well, and look at the distribution of AT_DROPOUT.
