### ISSUE TITLE
Memory footprint on MarkDuplicates?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/picard#1773]
Hello,

Our slurm cluster is now implementing more strict memory usage, and more actively killing jobs that exceed their request. MarkDuplicates is consistently getting killed, despite using -Xmx and -Xms. We're running something like this:

```
java -Xmx128g -Xms128g -Xss2m -jar picard.jar MarkDuplicates \
COMPRESSION_LEVEL=9 \
INPUT=input.bam \
OUTPUT=output.bam \
METRICS_FILE=metrics.txt
```

The process is getting regularly killed, with errors about exceeding memory. Should Xmx and Xms be sufficient to constrain MarkDuplicates?

Note: the issue isnt java itself dying due to exceeding memory. I realize we could change MAX_RECORDS_IN_RAM or SORTING_COLLECTION_SIZE_RATIO to reduce the memory footprint of the tool. So far as we can see, the problem seems to be picard exceeding the 128G and then slurm killing it. We are not having this issue with other Picard/GATK tools. 

Should there be a way to constrain memory on MarkDuplicates? Thanks for any ideas.

**Comment by gbggrant** [comment]
HI @bbimber, you are correct that configuring MarkDuplicates memory is challenging. This is in part because MarkDuplicates uses the parameter 'SORTING_COLLECTION_SIZE_RATIO' that no other Picard tool uses. Ultimately, you will probably need to reduce this argument value in order to solve your memory issues.

Here are some suggestions from another thread (some of this is irrelevant to your issue):
1) increase the amount of disk you give to the task.  I think it is possible that this is actually an out of disk space failure, not an out of memory failure, caused by a spill to disk of a SortingCollection
2) counterintuitively, reduce the amount of memory you give to the task.  MD tries to dynamically figure out how much data it can hold in memory, so adding memory to a task doesn’t actually help in out of memory situations with MD
3) if those don’t work, just keep decreasing the sorting_collection_size_ratio

Good luck!

George

**Comment by bbimber** [comment]
@gbggrant Thanks. For my own edification, why doesnt Xmx/Xms constrain it? Again, I'm not getting a java-based OOM error. The java process is using more than the memory allotted for the job (which is the value we use for Xmx/Xms), and slurm is killing the java process.

**Comment by mdbarnesUCSD** [comment]
@gbggrant could you please clarify how much memory the parameter SORTING_COLLECTION_SIZE_RATIO could potentially use? I am trying to figure out what size memory footprint I can expect when setting different values for SORT_COLLECTION_SIZE_RATIO. 

Thanks!

**Comment by TKsh6** [comment]
I have reduced `sorting_collection_size_ratio` to 0.01, but it still didn't work. I have no idea to solve this, could you please help me?
yours tk,
