### ISSUE TITLE
Possible MarkDuplicates bug: no optical duplicates found

### ISSUE THREAD

**Issue by gevro** [broadinstitute/picard#1848]
Hi, We're running MarkDuplicates v.2.27.4

with options: 
REMOVE_DUPLICATES=false \\
    METRICS_FILE=metrics.txt \\
    OPTICAL_DUPLICATE_PIXEL_DISTANCE=2500 \\
    ASSUME_SORT_ORDER=queryname \\
    CLEAR_DT=false \\
    REMOVE_SEQUENCING_DUPLICATES=true

on BAM files that are all run on the same Novaseq sequencer.

However, one set of samples finds READ_PAIR_OPTICAL_DUPLICATES, and the other set of samples is showing 0 READ_PAIR_OPTICAL_DUPLICATES in the metrics file. We cannot figure out why. All the properties of the two sets of data in the input BAM files seem identical, and everything was aligned and processed in the exact same pipeline.

![image](https://user-images.githubusercontent.com/47928628/206556049-15c06f35-9c92-42a7-b2c4-58b1b1458efb.png)

The only difference between the two sets of samples is the read name format.
 - The set of samples that are found to have optical duplicates have this format: 
 ```
A00887:522:HHJLFDRX2:2:2202:3233:22842
 ```
 - The set of samples that are NOT found to have optical duplicates have this format:
 ```
A00887:518:HGCKJDRX2:2:2268:10691:21731:TAAGTCTTA
```

The latter have an extra 8bp UMI. Could that be causing the issue? But UMI in the read name should not affect MarkDuplicates in any way.

Thanks.

**Comment by lbergelson** [comment]
@gevro That isn't surprising to me.  The readname is an important part of determining if something is an optical duplicate or not because it encodes the physical location of the read on the flow cell.  If you have read names that follow a non-standard naming scheme you might have to provide a custom parsing regex.  See the argument [`--READ_NAME_REGEX](https://gatk.broadinstitute.org/hc/en-us/articles/9570381778587-MarkDuplicates-Picard-#--READ_NAME_REGEX) which lets you specify how to parse alternative readname schemes.  

There's also a separate tool `UmiAwareMarkDuplicatesWithMateCigar` which might be appropriate for your use case although I know very little about it.

**Comment by gevro** [comment]
Thank you!
