### ISSUE TITLE
Sum of Which columns in MarkDulicates metrices gives us total reads?

### ISSUE THREAD

**Issue by Rohit-Satyam** [broadinstitute/picard#1866]
I see that Picard calculates the Percent Duplicates using `READ_PAIRS_EXAMINED` and `READ_PAIR_DUPLICATES` column as described [here](https://github.com/broadinstitute/gatk-docs/blob/master/blog-2012-to-2019/2016-03-18-Metrics_say_percent_%E2%80%93_Double-check_those_decimals_%E2%80%93_Fractions_everywhere.md?id=7264). However, I am not sure how this number `READ_PAIRS_EXAMINED` is calculated and why it doesn't matches total read that were given for alignment to STAR. For example I have these RNASeq samples

| LIBRARY    | Reads_Post_Trimming_R1_only | UNPAIRED_READS_EXAMINED | READ_PAIRS_EXAMINED | SECONDARY_OR_SUPPLEMENTARY_RDS | UNMAPPED_READS | UNPAIRED_READ_DUPLICATES | READ_PAIR_DUPLICATES | READ_PAIR_OPTICAL_DUPLICATES | PERCENT_DUPLICATION | ESTIMATED_LIBRARY_SIZE |
| ---------- | ------------------------------ | ----------------------- | ------------------- | ------------------------------ | -------------- | ------------------------ | -------------------- | ---------------------------- | ------------------- | ---------------------- |
| Sample1_R1 | 10682                          | 69                      | 9759                | 48731                          | 1777           | 28                       | 5884                 | 29                           | 0.602236            | 4334                   |
| Sample2_R1 | 29642                          | 306                     | 28535               | 324241                         | 1908           | 237                      | 13321                | 47                           | 0.468471            | 20065                  |

I wish to understand why `UNPAIRED_READS_EXAMINED + READ_PAIRS_EXAMINED != Reads_Post_Trimming_R1_only ` and if I wish to calculate the proportion of reads per sample as compared to total useful reads sequenced i.e. ` Reads_Post_Trimming_R1_only `, is formula `(READ_PAIR_DUPLICATES +UNPAIRED_READ_DUPLICATES) *100 / Reads_Post_Trimming_R1_only ` correct?

Or should I use  `(READ_PAIR_DUPLICATES + (UNPAIRED_READ_DUPLICATES/2)) *100 / Reads_Post_Trimming_R1_only `

**Comment by kockan** [comment]
Hi Rohit, you can check out how certain metrics such as `READ_PAIRS_EXAMINED`, `UNMAPPED_READS`, and `UNPAIRED_READS_EXAMINED` are updated here:

https://github.com/broadinstitute/picard/blob/62ec81cda59d4434604ee4f9c45d6882cd00c887/src/main/java/picard/sam/DuplicationMetrics.java#L264

Based on this, the correct formula to calculate `Reads_Post_Trimming_R1_only` should be `Reads_Post_Trimming_R1_only = READ_PAIRS_EXAMINED + (UNMAPPED_READS / 2) + (UNPAIRED_READS_EXAMINED / 2)`

If you try this on the sample table you've provided, you'll see that it works.

As you might have noticed, we don't count secondary and supplementary reads since they are just additional alignments for the same read.

For your second question, I'm not entirely sure what your objective is, but I believe `(READ_PAIR_DUPLICATES + (UNPAIRED_READ_DUPLICATES / 2)) * 100 / Reads_Post_Trimming_R1_only` would be more appropriate.
