### ISSUE TITLE
Problem with Picard tool for Collecting RNASeqMetrics 

### ISSUE THREAD

**Issue by annepureddy** [broadinstitute/picard#1926]
Hello,
I am using the STAR aligner to align bulk RNA-seq samples generated from Smart-Seq-2 protocol using the Nextera XT Dna library prep kit. 
I have no errors and am able to successfully generate all the output files.
Then I try to use the picard Collect RNA-seq metrics tool using:

```
  picard CollectRnaSeqMetrics \
    I= ${sample}.Aligned.sortedByCoord.out.bam \
    O=${sample}.output.RNA_Metrics \
    REF_FLAT="/Users/f006f9w/Dropbox (Dartmouth College)/Goods Lab/Projects/MFGM_NIH_Rimi/Bulk RNA-Seq/Bam_files/refFlat.txt" \
    STRAND=SECOND_READ_TRANSCRIPTION_STRAND \
    RIBOSOMAL_INTERVALS=GRCh38.p5.rRNA.interval_list
```
**However, my .RNA_metrics file does not have any coding, UTR or intronic bases.** It would be great if you could please let me know what the issue is here.

```
## METRICS CLASS	picard.analysis.RnaSeqMetrics
PF_BASES	PF_ALIGNED_BASES	RIBOSOMAL_BASES	CODING_BASES	UTR_BASES	INTRONIC_BASES	INTERGENIC_BASES	IGNORED_READS	CORRECT_STRAND_READS	INCORRECT_STRAND_READS	NUM_R1_TRANSCRIPT_STRAND_READS	NUM_R2_TRANSCRIPT_STRAND_READS	NUM_UNEXPLAINED_READS	PCT_R1_TRANSCRIPT_STRAND_READS	PCT_R2_TRANSCRIPT_STRAND_READS	PCT_RIBOSOMAL_BASES	PCT_CODING_BASES	PCT_UTR_BASES	PCT_INTRONIC_BASES	PCT_INTERGENIC_BASES	PCT_MRNA_BASES	PCT_USABLE_BASES	PCT_CORRECT_STRAND_READS	MEDIAN_CV_COVERAGE	MEDIAN_5PRIME_BIAS	MEDIAN_3PRIME_BIAS	MEDIAN_5PRIME_TO_3PRIME_BIAS	SAMPLE	LIBRARY	READ_GROUP
923592354	902491934	1438	0	0	0	902490496	0	0	0	0	0	0	0	0	0.000002	0	0	0	0.999998	0	0	0	0	0	0	0			
```
Thank you for the help!

**Comment by kockan** [comment]
The refflat itself looks fine, but I suspect it might not be read/processed properly by the program. It seems to run and produce some output, so the input bam and rRNA interval list don't look too suspicious at this point. There is a whitespace after `I=` which gives a very slight uneasiness to me but again, since we have _some_ metrics out of the alignment file, it should be okay.

Given that `PF_ALIGNED_BASES`, `RIBOSOMAL_BASES`, and `INTERGENIC_BASES` are reported (as non-zero values) and the default label of a base not overlapping with rRNA or a gene is intergenic, the most likely culprit is still the refflat file. It looks like the path to the refflat contains some whitespaces, so might be worth checking this out. Could you copy the file locally to something like "test_refflat.txt"  and try again? If this also fails, looking at the program log and the full header from the metric output file might also help.

**Comment by kockan** [comment]
Most likely issue is that the refflat is somehow malformed (whitespace, etc.) or there is an issue reading it due to path, etc. Closing for now, reopen if user has updates.
