### ISSUE TITLE
Optical duplicates

### ISSUE THREAD

**Issue by Nitin123-4** [broadinstitute/picard#1962]
Hi team,

I want to understand how Picard is deciding this is a optical duplicate in case of pattern flow cells specially NovaSeq X Plus 25B.
I understand that it looks for the position on the tile and see if the reads are within certain distance that is 100 by default and can be 2500 for pattern flow cells. 

1. Is it possible that two complete different reads from two different fragments can also be considered as optical duplicate as they are close proximity based on --OPTICAL_DUPLICATE_PIXEL_DISTANCE parameter?
2. If REMOVE_DUPLICATES is true, all duplicates are removed. In this case will it also remove optical duplicates?
3. If we set --OPTICAL_DUPLICATE_PIXEL_DISTANCE to 2500 will it not give more optical duplicates ?

Only concern is if the two reads are coming from two different fragments and are in close proximity and considered as optical duplicates and  REMOVE_DUPLICATES: true removes them will negatively affect in the case of NovaSeq X Plus 25B flow cell data.

Please help with this.

**Comment by yfarjoun** [comment]
1. no. not possible. "optical duplicate" is a type of duplicate, so the reads would need to be duplicates _first_ and then, they might be counted as "optical" if that is appropriate. under your premise that  the reads come from "two different fragments", I presume that the start/stop positions are different between the pairs of reads under discussion, so they will not be considered duplicates.
2. yes.
3. yes, it will give more _optical_ duplicates, but the total duplication rate will remain the same.

Some notes: 
a. optical duplicates counts are used for library-size estimation _only_. All duplicates, optical or otherwise, are marked as duplicates and treated equally downstream.
b. if you want to know if a specific read was considered an optical duplicate (and even which "duplicate set" it was part of) you can run markDuplicate with TAGGING_POLICY and then look at DT (for the type) and DI (for the set "index") of each duplicate read.

**Comment by Nitin123-4** [comment]
Thanks for your response. 
1. Can I consider all the optical duplicates are the subset of PCR duplicates?
2. Can any two reads that don't align on the same location on the reference genome still be classified as optical duplicates?
3. if there is any explanation for why --OPTICAL_DUPLICATE_PIXEL_DISTANCE is 2500 recommended for pattern flow cells or in case of 25B flow cell; please share it.

**Comment by yfarjoun** [comment]
1. no. Optical Duplicates are supposed to be duplicates that are due to either actual "optical" issues (such as large "blob"-clusters registering as two clusters on the sequencer, or other flow-cell-local issues, for example on the patterned flowcell it was found that there seems to be "reseeding" where templates from once well start a colony in a nearby well. In picard all these spatially-proximal duplicates are counted as "optical" exactly because the assumption is that they are _not_ PCR duplicates. Optical duplicates should have arisen from a single PCR product. 
2. Not in the standard processing of duplicates (I think that FLOW_MODE introduces a slightly different logic with which I'm not 100% familiar). in the standard processing two read-pairs have to have the same unclipped 5'-end positions and same "orientation" (the directions of the alignments in their contigs) in order to be considered duplicates (of any kind, PCR, or optical)
3. If I recall correctly, this was found empirically, when the first patterned flowcells came out, we examined the dependence of the  number of optical duplicates on OPTICAL_DUPLICATE_PIXEL_DISTANCE and found that it plateaued around 2500 so we picked that number. I am not aware of followup experiments with later models. You may want to take a look at this yourself to be sure that the number works for you.

**Comment by Nitin123-4** [comment]
Thanks a lot for the detailed response. Really helpful.
