### ISSUE TITLE
CollectInsertSizeMetrics labels wrong RF reads

### ISSUE THREAD

**Issue by LingjunM** [broadinstitute/picard#1983]
----

### documentation request

----

### Tool(s) involved
CollectInsertSizeMetrics

### Description 
With the follow command I get a plot with blue region(i.e. RF reads).
`picard CollectInsertSizeMetrics I=good.bam O=m0.05.stats H=M0.05.pdf M=0.05
`
However when check the original file I find the tool seems to label counts randomly.

```
$ head -n +20 m0.05.stats | tail -9
insert_size     All_Reads.fr_count      All_Reads.rf_count
18      0       2
19      2       3
20      2       0
21      1       1
22      1       0
23      1       2
24      3       4
25      7       8
```

Check the reads 

```
$ samtools view good.bam|cut -f 1-9|awk '$9 == "-20"'
A00509:287:H73GHDRXY:1:2173:15691:30765 99      chr14   44916236        31      20M     =       44916236        -20
A00509:287:H73GHDRXY:1:2173:15691:30765 147     chr14   44916236        31      20M     =       44916236        -20
A00509:287:H73GHDRXY:1:2145:4010:19398  99      chr14   81439563        34      20M     =       81439563        -20
A00509:287:H73GHDRXY:1:2145:4010:19398  147     chr14   81439563        34      20M     =       81439563        -20

$ samtools view good.bam|cut -f 1-9|awk '$9 == "-21"'
A00509:287:H73GHDRXY:1:2239:3061:17722  99      chr2    176080440       32      21M     =       176080440       -21
A00509:287:H73GHDRXY:1:2239:3061:17722  147     chr2    176080440       32      21M     =       176080440       -21
A00509:287:H73GHDRXY:1:2158:8431:16313  163     chr14   60898125        30      21M     =       60898125        -21
A00509:287:H73GHDRXY:1:2158:8431:16313  83      chr14   60898125        30      21M     =       60898125        -21
```

So how does it label fr/fr counts? I dont get information from gatk's documentation

----

**Comment by yfarjoun** [comment]
The SAM flag (column 2) is your friend here. For a nice page explaining what that number means go [here](https://broadinstitute.github.io/picard/explain-flags.html). 

FR means read1 is Forward-strand, and read2 is Reverse-strand.
RF means read1 is Reverse-strand, and read2 is Forward-strand.

If you go through the details you'll see that 99 (or 147) for that matters imply FR (which is why insert size 20 has 2 FR pairs)
while 163 and 83 imply RF (which is why insert-size 21 has 1 FR and 1 RF. )

**Comment by LingjunM** [comment]
Thanks for your clarification,I think I understand what you mean. I will explain at first and ask a new question.
So picard considers "1st to reverse 2nd to ref" as RF, and "1st to ref 2nd to reverse" as FR.
As the picture below.

![image](https://github.com/user-attachments/assets/2631c003-569b-4adc-97d5-da36fb85c90a)


But:
1. I'm dealing with ATACseq data,so 99/147 reads and 83/163 reads should be equal .So the plot will be a mixture of blue and red region as explained above,it turns out wrong.That's why I wants to get a look at stats file and sorry for not posting my result at first.

```
$ samtools view good.bam|cut -f 2|sort|uniq -c
 721643 147
 718508 163
 718509 83
 721644 99
```
![image](https://github.com/user-attachments/assets/a2bfdb20-88d9-49a2-b188-8aec5409425b)




2. According  to the [GATK documentation](https://gatk.broadinstitute.org/hc/en-us/articles/360035531792-Paired-end-or-mate-pair), RF reads should be outward. Why does Picard have a different behavior when treating overlapped reads and dovetailed reads?
That is
For just overlapped or gapped reads(long insert size),no matter 1st strand aligned to which strand,they are all red("FR"), but for dovetailed reads(short insert size),it distinguishes them by1st strand's directionality.I guess there maybe some other standard

![image](https://github.com/user-attachments/assets/72b7ef5a-87e8-441f-bb62-81dad4a7fa7b)

**Comment by yfarjoun** [comment]
I'm sorry, I gave you the wrong interpretation of FR vs. RF (it's confusing since there are indeed two different interpretations...) 

For the purpose of insert-size metric collection, FR and RF (and their more rare cousin "TANDEM") indicate the oriantations of the reads relative to the insert. From the code: 
```
   public static enum PairOrientation
    {
        FR,     // ( 5' --F-->       <--R-- 5'  )  - aka. innie
        RF,     // (   <--R-- 5'   5' --F-->    )  - aka. outie
        TANDEM // ( 5' --F-->   5' --F-->  or  (  <--R-- 5'   <--R-- 5'  )

    }
```
The way that the orientation is defined is as follows: 
if the two reads have the same strand, the orientation is TANDEM.
otherwise, one of them is FORWARD and the other is REVERSE. 
find out the 5' position of the two reads (the position of the earliest cycle in the read which is aligned) if that position of the FORWARD strand is smaller than that of the REVERSE, then the orientation is FR, otherwise it's RF. 

(in other words, FR and RF indicate the position along the genome of the 5' ends of the Forward, and Reverse reads)
----
This brings us to looking at your example and trying to understand what's going on. 

I think that there's a small bug in the implementation of the RF/FR orientation in the picard code-base (thanks for the tip!) 

In addition your SAM file seems to be **invalid**. In particular, the TLEN is negative for both records of the same query name while the SAM spec specifically states that they should differ in sign: 

<img width="633" alt="image" src="https://github.com/user-attachments/assets/d411e8ad-122b-4071-aa72-c852a7899d56">

However, I think that the bug is more serious and I'll see if I can fix it.

**Comment by yfarjoun** [comment]
To fix your issue, I suggest you run FixMateInformation on your bam (best if you do it before coordinate sorting the bam) and only _then_ run CollectInsertSizeMetrics.

**Comment by LingjunM** [comment]
Thanks.I have tried the following code to test and you are right.
`awk 'BEGIN {OFS="\t"} $2 == 163 && $9 < 0 { $9 = -$9} 1' good.sam > change.sam `
![ch](https://github.com/user-attachments/assets/58a43ff0-6a41-4f94-a895-28783ca3044a)

The bam file i use is downloaded from encode(already sorted) as an ATAC workshop states so it maybe an old feature of  bowtie to sign both TALEN  negative values.And why there are so many records with same coordinates can be interpreted as short segments cut by Tn5 enzyme used in ATACseq.
If i encounter a similar problem in my own analysis， i will try your advice.

**Comment by yfarjoun** [comment]
No problem. 

In generaI, highly recommend running picard's ValidateSamFile (even though it can be slow) on your bam files and even more-importantly on file you download. You'll often find that invalid BAMs cause odd outputs and getting into the habit of validating your inputs/outputs is a good way of avoiding this. 

This is particularly important when you use awk and other text-manipulation programs as part of your pipeline....

Good luck!
