### ISSUE TITLE
MAX_OUTPUT='null' kills ValidateSamFile

### ISSUE THREAD

**Issue by artgoldberg** [broadinstitute/picard#204]
$ java -Xmx4096m -jar "$PICARD_HOME/ValidaSamFile.jar" INPUT="$bam" OUTPUT="${base}.ValidateSamFile.out" MAX_OUTPUT='null'

stderr:
    [Thu Apr 30 12:27:00 EDT 2015] Executing as goldba06@interactive5 on Linux 2.6.32-358.23.2.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.7.0_03-b04; Picard version: 1.112(1930) IntelDeflater
    [Thu Apr 30 12:27:00 EDT 2015] net.sf.picard.sam.ValidateSamFile done.     Elapsed time: 0.00 minutes.
    Runtime.totalMemory()=1009909760
    To get help, see http://picard.sourceforge.net/index.shtml#GettingHelp
    Exception in thread "main" java.lang.NullPointerException
	at net.sf.picard.sam.ValidateSamFile.doWork(ValidateSamFile.java:148)
	at     net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:179)
	at net.sf.picard.sam.ValidateSamFile.main(ValidateSamFile.java:101)

Although it's documented in http://broadinstitute.github.io/picard/command-line-overview.html

**Comment by vdauwera** [comment]
@artgoldberg We have a new policy for Picard tools support. For initial questions and bug reports, we ask that you please post in the [GATK forum](http://gatkforums.broadinstitute.org/post/question). If we find that there is an actual bug that requires code changes we'll open a github issue ourselves. This helps us manage support to the community.

When you post this to the [GATK forum](http://gatkforums.broadinstitute.org/post/question), please clarify whether the issue still happens if you don't specify the MAX_OUTPUT argument. Thanks!
