### ISSUE TITLE
in GC bias show metrics for deduped and non-deduped reads 

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#342]

**Comment by nh13** [comment]
@yfarjoun could this be another "level" and therefore modify or extend `MultiLevelCollector` and `PerUnitMetricCollector`?  It may then be useful for other tools?

**Comment by yfarjoun** [comment]
Interesting idea. Though it would be nice to have the plots contain both
data, no?

**Comment by nh13** [comment]
In some cases it would, like for GC bias plots, but the same could be said for any metric level.

**Comment by yfarjoun** [comment]
@jabbarish another interesting issue, I think.

**Comment by zstudent** [comment]
As far as we understand it, CollectGcBiasMetrics calculates GC bias statistics for different levels (all reads, sample, library, read group) and produces two output txt files (details and summary) with statistics and pdf file with data plots. Current version doesn't check whether a read is a duplicate or not at any level. The key point is to collect information about the duplicate flag for all levels (one level is selected per execution) and plot two batches of charts (one includes all reads according to level and the other includes only non-duplicates according to level). 

We propose several changes in this metric:
1. New command line option NON_DUPLICATES that has 'false' default value and true if user would like to calculate GC bias statistics for both cases (for all reads and for non-duplicates).
2. If that option is true output files will contain additional information for non-duplicates case with extra prefix.
3. New unit test to validate the results. 

Also, the proposed changes contain solution for the other issue https://github.com/broadinstitute/picard/issues/342: there is an exception while processing reads, because of symbol '*' in SEQ field. SAM/BAM format specification allows this, but CollectGcBiasMetrics can not process such situation correctly. 

We propose to omit reads with '*' is SEQ field and log message. Also, we added new unit test to check correctness. 

All proposed improvements do not effect the performance.

@yfarjoun if this sounds good to you, we will create PR with this changes.

**Comment by jabbarish** [comment]
As far as we understand, CollectGcBiasMetrics calculates GC bias statistics for different levels (all reads, sample, library, read group) and produces two output txt files (details and summary) with statistics and pdf file with data plots. Current version doesn't check whether a read is a duplicate or not at any level. The key point is to collect information about a duplicate flag for all levels (one level is selected per execution) and plot two batch of charts (one includes all reads according to level and the other includes only non-duplicates according to level). 

We suggest several changes in this metric:
1. New command line option NON_DUPLICATES that false default and true if user would like to calculate GC bias statistics for both cases (for all reads and for non-duplicates).
2. If that option is true output files will contain additional information for non-duplicates case with extra prefix.
3. New unit test to validate the results. 

Also, our changes contain solution for other issue https://github.com/broadinstitute/picard/issues/342: there is an exception while processing reads, because of symbol '*' in SEQ field. SAM/BAM format specification allows this but CollectGcBiasMetrics can not process such situation correctly. 

We propose to omit reads with '*' is SEQ field and log message. Also, we added new unit test to check correctness. 

All proposed improvements do not effect the performance.

@yfarjoun if this sounds good to you, we will create PR.  Sorry for the previous message, wrong account :)

**Comment by yfarjoun** [comment]
This sounds good to me. except for the name of the parameter. I'm wondering
if you could implement it the way @nh13 described it as an additional
"layer" where the regular behavior would be "All" and the one where
non-duplicate reads are collected as well would be ["All","Non-Duplicates"]
or something like that.

I worry that the NON_DUPLICATES=false argument would seem like we are
ignoring non-duplicates.

**Comment by tfenne** [comment]
@yfarjoun I'm curious why you want this?  I would think that when looking at GC bias issues you would want to always include duplicates because we are mostly talking about bias in amplification, which would lead to higher levels of duplicates in regions that the prep is biased towards.  I worry that adding this option will mislead people since it's the default of most tools to ignore duplicates, whereas in this case they are a critical piece of the puzzle.

**Comment by yfarjoun** [comment]
I agree that bias due to the amplification is an important piece of the
puzzle, but perhaps not all of it?

As you know better than me, duplication can arise due to many other issues:
optical, "pad-hoping", and reference errors, by looking at the
de-duplicated bias I can see what bias the downstream tools will see rather
than the bias caused by upstream. I guess it's more of a predicting
downstream quality instead of diagnosing upstream problems. I agree with
you that in many cases all the reads are important. We should make sure
that the option makes this clear.

**Comment by nh13** [comment]
How about just filtering out the duplicates and streaming the reads into this tool?

**Comment by yfarjoun** [comment]
@nh13 The desire to having the output plots contain both metrics is made complicated by splitting this into two different calls, but if both you and @tfenne think that this would not be a positive addition to the repository, I'm not strongly convinced otherwise to object.

**Comment by zstudent** [comment]
I need to note that ( if we understood you correctly) we have implemented read filtering by duplicate flag as @nh13  suggested in his last comment. This doubles number of plots in the resulting pdf.  

We agree with @yfarjoun: the option name NON_DUPLICATES is ambiguous and may mislead users. We can suggest several alternative names: (Maybe one of the following is cleaner) 
ADD_IGNORING_DUP, 
INCLUDE_REMOVING_DUP,  
INCLUDE_NON_DUPLICATES, 
IGNORE_DUPLICATES). 

We think that enabling this option will extend current functionality and allow to get two plots per level at the same time: one is the usual one and the other excludes duplicates. If this option would have extra level it would be unclear what is the usage of this level.  Lets consider LEVEL=ALL_READS  LEVEL=SAMPLE  LEVEL=NON_DUPLICATES, what behavior is expected? 

As we understand it maybe useful to compare two plots with and without duplicates and in this case this option as boolean variable is suitable. We may provide you with PR to clarify what we have meant, the necessary code changes are already done.

**Comment by jabbarish** [comment]
I need to note that ( if we understood you correctly) we have implemented read filtering by duplicate flag as @nh13 suggested in his last comment. This doubles number of plots in the resulting pdf.

We agree with @yfarjoun: the option name NON_DUPLICATES is ambiguous and may mislead users. We can suggest several alternative names: (Maybe one of the following is cleaner) 
ADD_IGNORING_DUP, 
INCLUDE_REMOVING_DUP,

INCLUDE_NON_DUPLICATES, 
IGNORE_DUPLICATES).

We think that enabling this option will extend current functionality and allow to get two plots per level at the same time: one is the usual one and the other excludes duplicates. If this option would have extra level it would be unclear what is the usage of this level. Lets consider LEVEL=ALL_READS LEVEL=SAMPLE LEVEL=NON_DUPLICATES, what behavior is expected?

As we understand it maybe useful to compare two plots with and without duplicates and in this case this option as boolean variable is suitable. We may provide you with PR to clarify what we have meant, the necessary code changes are already done.

**Comment by yfarjoun** [comment]
To make sure that folks always get the version that has duplicates, I'd
vote for the boolean option and have ALSO_IGNORE_DUPLICATES as a boolean
flag.

Thanks for this!

Yossi.
