### ISSUE TITLE
Have fingerprint metrics suffix be command-line options

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/picard#380]
We need to allow the possibility for the metrics suffix from CheckFingerprint to be different.
See this PR for more information: https://github.com/broadinstitute/picard/pull/379/files#r49205323

**Comment by yfarjoun** [comment]
perhaps have the suffixes as optional parameters with the static variables
as the default values?

**Comment by nh13** [comment]
@yfarjoun to keep consistent with other tools, I think the full file paths should be specified.  I think having different behavior across tools or different input mechanisms confuses users.  @vdauwera what do you think?

**Comment by nh13** [comment]
I think preserving the default behavior is valuable (since likely it is used in production) so I implemented both mechanisms.

**Comment by vdauwera** [comment]
There's definitely some potential for confusion here -- I'd recommend including a worked-out example that specifically details what the file names will be depending on the options used.

**Comment by nh13** [comment]
@vdauwera are you talking about the discussion here, or the pull request I just submitted.  If the former, can you comment on the latter?  I think the PR brings this tool in line with other tools in Picard.

**Comment by vdauwera** [comment]
@nh13 To be honest I was confused by both, and I'm not sure I'm clear on the behavior in your PR. 

Generally speaking the behavior of Picard metrics tools re: output file naming conventions tends to be confusing for new users. Obviously consistency helps because once you get it for one, you got it for the rest. But getting it for that first one is still a hump. We recently (finally!) completed our first round of doc improvements (touching ~55 tools) which included adding examples for the file naming for some tools, but I think we could do more on that front. 

Going forward it would be great to see explicit examples added systematically whenever the behavior is not simply "you get the name that you give" (i.e. if you specify "metrics.txt" and out comes "metrics.txt", no need to spell it out) for increased transparency and great justice.

**Comment by nh13** [comment]
@vdauwera I definitely see the improved documentation (ex. `CollectGcBiasMetrics`), kudos.  I would definitely support the addition of similar documentation to `CheckFingerprint` when it is out of alpha, though frankly, I don't believe I am best suited to write that documentation and it seems like a burden to be honest for such a small change to an alpha tool that fixes something that perhaps could have been addressed in the initial import pull request review.  

For now, I suggest the incremental improvement of making the functionality in `CheckFingerprint` consistent with tools like `CollectGcBiasMetrics` and pushing comprehensive documentation for this tool to be a future improvement (perhaps by someone on your team :+1:?).  Does that sound reasonable?

**Comment by vdauwera** [comment]
@nh13 My team can indeed handle taking the doc to the next level, but I would like to see some clarifications on key points -- basically what @yfarjoun raises in his review comments -- that are relevant to the changes you are making.

**Comment by yfarjoun** [comment]
resolved by #381
