### ISSUE TITLE
picard-1.141 Cram Output for FastqToSam

### ISSUE THREAD

**Issue by vcaropr1** [broadinstitute/picard#431]
I have been messing with the cram implementation into picard and was wondering if the output of FastqToSam can indeed be a cram file or not.  I know for SamFormatConverter the output can be a cram file, but when trying the same method FastqToSam seems to output a bam sized file with a .cram ending.  The code below is what I ran:

java -jar picard FastqToSam 
FASTQ=read1.fastq 
FASTQ2=read2.fastq
SORT_ORDER=coordinate
OUTPUT=sample.cram
SAMPLE_NAME= sample_name
PLATFORM_UNIT= read_index
LIBRARY_NAME=library
PLATFORM=ILLUMINA

Again, I am using 1.141 and not sure if this was resolved in 2.0.1 or if this capability isn't there.  

Thanks!

**Comment by cmnbroad** [comment]
I'm not sure what the official support status for writing (or reading) CRAM in picard tools is, but it looks like most of them are still using makeSAMOrBAMWriter, which isn't really equipped for writing CRAM files since doing so requires a reference. It also has a [bug](https://github.com/samtools/htsjdk/issues/366) that results in behavior exactly as you describe (writes BAM encoded contents even if the output file has a .cram extension). You can verify this is whats happening by running "od -c -N 4 youroutput.cram". An actual CRAM file produced by htsjdk will output "0000000   C   R   A   M" but for BAM will produce less unrecognizable compressed output like "0000000 037 213  \b 004".

**Comment by vcaropr1** [comment]
Yup you are definitely right.  This file created is just a bam file with a .cram extension.
