### ISSUE TITLE
MarkDuplicates throws error using cram files

### ISSUE THREAD

**Issue by dekling** [broadinstitute/picard#433]
Get the following error when using cram file for this tool:

Exception in thread "main" htsjdk.samtools.cram.CRAMException: A reference source is required for CRAM files
    at htsjdk.samtools.CRAMIterator.<init>(CRAMIterator.java:86)
    at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:130)
    at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:146)
    at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:152)
    at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:273)
    at picard.sam.markduplicates.util.AbstractMarkDuplicatesCommandLineProgram.openInputs(AbstractMarkDuplicatesCommandLineProgram.java:205)
    at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:307)
    at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:155)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
    at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
-bash:gsa3:/humgen/gsa-scr1/dkling 622 $ 

Here is the server command line and test files:
-bash:gsa3:/humgen/gsa-scr1/dkling 621 $ java -jar picard.jar MarkDuplicates I=/humgen/gsa-scr1/dkling/cram/pruned_snippet.cram O=/humgen/gsa-scr1/dkling/cram/pruned_snippet_md.bam M=/humgen/gsa-scr1/dkling/cram/pruned_snippet_md.txt R=/humgen/gsa-scr1/pub/bundle/2.8/b37/human_g1k_v37.fasta.gz

Picard jar is in gsa3:/humgen/gsa-scr1/dkling 

-Thanks

P.S.  It worked fine with a bam file: /humgen/gsa-scr1/dkling/cram/pruned_snippet.bam

**Comment by yfarjoun** [comment]
This is going to be a problem with all picard tools. I think that the best
solution would be to add the REFERENCE to the default SamReaderFactory, but
I'm not sure how to do that. @tfenne? @droazen? any ideas how to do that?

in lieu of doing it that way, it shouldn't be too difficult to go over all
the uses of SamReaderFactory and add

.referenceSequence(REFERENCE_SEQUENCE)

to the call. it protects against null, and so no more protection is
needed...


On Thu, Feb 11, 2016 at 2:38 PM, David E. Kling <notifications@github.com>
wrote:
>
> Get the following error when using cram file for this tool:
>
> Exception in thread "main" htsjdk.samtools.cram.CRAMException: A
reference source is required for CRAM files
> at htsjdk.samtools.CRAMIterator.(CRAMIterator.java:86)
> at htsjdk.samtools.CRAMFileReader.(CRAMFileReader.java:130)
> at htsjdk.samtools.CRAMFileReader.(CRAMFileReader.java:146)
> at htsjdk.samtools.CRAMFileReader.(CRAMFileReader.java:152)
> at
htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:273)
> at
picard.sam.markduplicates.util.AbstractMarkDuplicatesCommandLineProgram.openInputs(AbstractMarkDuplicatesCommandLineProgram.java:205)
> at
picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:307)
> at
picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:155)
> at
picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
> at
picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
> at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
> -bash:gsa3:/humgen/gsa-scr1/dkling 622 $
>
> Here is the server command line:
> -bash:gsa3:/humgen/gsa-scr1/dkling 621 $ java -jar picard.jar
MarkDuplicates I=/humgen/gsa-scr1/dkling/cram/pruned_snippet.cram
O=/humgen/gsa-scr1/dkling/cram/pruned_snippet_md.bam
M=/humgen/gsa-scr1/dkling/cram/pruned_snippet_md.txt
R=/humgen/gsa-scr1/pub/bundle/2.8/b37/human_g1k_v37.fasta.gz

**Comment by droazen** [comment]
@yfarjoun We solved this in the GATK4 ports of the Picard tools by centralizing creation of SAMReaders in a utility method, and enforcing a convention that all Picard tools must create their SAMReaders via that utility. The utility method guarantees CRAM compatibility.

(Relates to https://github.com/broadinstitute/gatk/issues/1210!)

**Comment by cmnbroad** [comment]
Also the Picard tools would need analogous changes for output; most of them
should probably be changed from makeSAMOrBAMWriter to makeWriter, which
accepts a reference.

On Thu, Feb 11, 2016 at 3:58 PM, droazen <notifications@github.com> wrote:

> @yfarjoun <https://github.com/yfarjoun> We solved this in the GATK4 ports
> of the Picard tools by centralizing creation of SAMReaders in a utility
> method, and enforcing a convention that all Picard tools must create their
> SAMReaders via that utility. The utility method guarantees CRAM
> compatibility.
>
> (Relates to broadinstitute/gatk#1210
> <https://github.com/broadinstitute/gatk/issues/1210>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/picard/issues/433#issuecomment-183057515>
> .
>



-- 
Chris Norman
Software Engineer/Temp
Broad Institute of MIT and Harvard
email: cnorman@broadinstitute.org <bhill@broadinstitute.org>

**Comment by yfarjoun** [comment]
hmmm. so what should we do here? we need to solve this in picard soon if we
really want to support cram...right?

**Comment by tfenne** [comment]
@yfarjoun: I would suggest 
1. `makeSAMorBAMWriter` should be adapted behind the scenes to also support CRAM writing, since it was always intended to be "make the appropriate writer based on file extension" - just back in the day that was only SAM or BAM.
2. Add a [static] default reference sequence to SAMFileWriterFactory (and SamReaderFactory?) and have this set by `CommandLineProgram` when `REFERENCE_SEQUENCE` is non-null and/or `Defaults.REFERENCE_FASTA` is set.
3. Have the default reference sequence used if one is not provided explicitly.

That should get things working pretty quickly with minimal invasive changes.  Specifically it would be _very bad_ to suddenly require `REFERENCE_SEQUENCE` be provided to all Picard programs even when not reading/writing CRAM.

From there it's probably worth reviewing the factories, deprecating some things and thinking about a longer term migration.

**Comment by cmnbroad** [comment]
htsjdk already knows how to navigate the CRAM reference [fallback chain](https://github.com/samtools/htsjdk/blob/fbe81caff4abf0ef29cf6c769f28a300daed73b1/src/java/htsjdk/samtools/cram/ref/ReferenceSource.java#L66) when an explicit reference isn't provided, and to throw if none of the fallbacks are enabled. At some point embedded CRAM references will be supported, and it will have to be updated to know how to handle those as well. Ideally consumers of htsjdk shouldn't have to worry about any of that.

I  did just notice that the fallback code isn't currently called by the writer factory, only the reader, but it should be - we've been evolving the CRAM code somewhat piecemeal and thats an oversight.

My 2 cents, I'd propose:

-Change Picard to use makeWriter. That change itself should be pretty easy (its the test writing thats time consuming); it won't require expanding the surface area of the htsjdk API; and it does just what we want. It only requires a reference for CRAM, otherwise the reference can be null.
-Fix the current makeSAMorBAMWriter [bug](https://github.com/samtools/htsjdk/issues/366) that causes it to encode .bam contents to a .cram file, by changing it to either throw on CRAM extensions, or use the fallback code instead, which would usually throw for CRAM anyway since there would be no default reference most of the time.

**Comment by yfarjoun** [comment]
This sounds good to me.

**Comment by nh13** [comment]
@yfarjoun which proposal?

**Comment by yfarjoun** [comment]
I didn't see this as two conflicting proposals, but perhaps I misunderstood
something.

AFAICT @cmnbroad suggested that makeWriter be used instead of
makeSamOrBamWriter, this sounds reasonable, though perhaps it's worth
deprecating makeSamOrBamWriter altogether and moving it's code into
makeWriter?
The reference will still be picked up according to @tfenne's suggestion.

the bug should be fixed regardless, in a separate PR.

**Comment by vdauwera** [comment]
Hellooooooo we still have users falling over this bug. Any plans to fix it? Is there a PR somewhere I'm not aware of?

**Comment by marchoeppner** [comment]
This still seems to be unresolved?
