### ISSUE TITLE
How many people access explain-flags.html per day?

### ISSUE THREAD

**Issue by JohnLonginotto** [broadinstitute/picard#721]
Hello Picard team!

Not an actual issue, but I would be interested to know (and i'm sure others would to) how many hits to broadinstitute.github.io/picard/explain-flags.html you receive on average per day.

I would estimate, oooo, 75? I wouldn't be surprised if I was off by a factor of 10 though, in either direction :)

All the best!

**Comment by vdauwera** [comment]
I don't think we track page views -- unless github does it automatically in a way I don't know about? If someone knows I'm interested to find out...

**Comment by yfarjoun** [comment]
https://github.com/isaacs/github/issues/320

doesn't look like it....

**Comment by vdauwera** [comment]
Hmm. Didn't know about the [Traffic](https://github.com/broadinstitute/picard/graphs/traffic) page, good to learn that at least. But it's a bit pants. The "Popular Content" is too general to be useful, and it doesn't track gh-pages.

We could add a Google Analytics tracker to the gh-pages if there's interest in that.

**Comment by yfarjoun** [comment]
would the data be public?

**Comment by vdauwera** [comment]
No, I think you'd have to log into the google account that the tracker is tied to to see results. Unless we expose the results (presumably this is possible). But that would probably involve more effort than we can spare right now.

**Comment by JohnLonginotto** [comment]
Ah, OK, no problem. I mean, personally I would definitely track those sorts of metrics because you'll see what sorts of usage your web tools are getting, maybe even perhaps getting stats on the main Picard help pages by counting visits to #some_section of the manual separately from #some_other_section. The free analytics program I use (Piwik) can to this i think. I'm sure GA can too.

Regarding the question if it would be kept private or not - hehe, i'm not about to ask the Broad Institute start sharing all of their private information with the world - however... the reason I wanted to know this statistic was so that I might quote it in my thesis about how people find working with bitflags difficult and non-intuitive, and as such pages such as this exist (and are/are not popular). I was 50:50 whether I should even ask, as it's a lot of work to finish a perfectly good sentence off. I think if you did share some portion of the data publicly, it would encourage more meta-bioinformatics questions to receive answers.

**Comment by vdauwera** [comment]
Hi @JohnLonginotto; I don't think we'd mind sharing that information, it's just a question of taking the time to set it up, versus other priorities like working on the actual tools. We track those metrics for GATK because we built a dedicated website for it, whereas the Picard pages are really just piggy-backing on the github repo (in a way that is technically really awkward). 

So I don't think we can give you a number, but if you're wiling to take a "pers. comm.", I can tell you based on my experience doing full-time support for GATK (and more recently for Picard) for over 4 years, that a majority of users who are not primarily trained in bioinformatics find the bitflags thing very unintuitive and confusing. We don't get that many questions about in the forum because most people never really have to look at the flags unless something goes wrong -- and even then there are many programs (like IGV) that will seamlessly convert the flags to meaningful/human-readable terms. So it's a problem that is largely invisible because people manage to avoid having to deal with it at all. I don't know whether that hurts or helps your argument, but there you go :)
