### ISSUE TITLE
Picard build failure

### ISSUE THREAD

**Issue by NGS-Newbie** [broadinstitute/picard#777]
I downloaded the latest Picard release from https://broadinstitute.github.io/picard/ after I run ./gradlew shadowjar the build fails with the following message -

macbook:picard-2.9.0 User1$ ./gradlew shadowjar

FAILURE: Build failed with an exception.

    Where: Build file '/Users/User1/Documents/picard-2.9.0/build.gradle' line: 20

    What went wrong: An exception occurred applying plugin request [id: 'org.ajoberstar.grgit', version: '1.4.2']

        Failed to apply plugin [id 'org.ajoberstar.grgit'] One of setGitDir or setWorkTree must be called.

    Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Any ideas how I could fix it?

Any help is highly appreciated! Thanks!

**Comment by lbergelson** [comment]
That happens when you're not building it in a git clone directory.  The build looks for for the .git subdirectory because it uses repository history to assign version numbers  and to communicate with github for doing releases.  

I would either try git cloning it and then building it again:
```
git clone https://github.com/broadinstitute/picard.git
cd picard
./gradlew shadowJar
``` 

or if you don't care about building it an just want to use picard you can download a prebuilt jar here: https://github.com/broadinstitute/picard/releases/download/2.9.0/picard.jar

**Comment by NGS-Newbie** [comment]
BUILD SUCCESSFUL! 
Thanks so much, Ibergelson!!

**Comment by lbergelson** [comment]
👍

**Comment by Sunhh** [comment]
Thank you!

**Comment by 996continue** [comment]
Thank you!
