### ISSUE TITLE
How should I cite picard when refering to its use on a paper?

### ISSUE THREAD

**Issue by el42008** [broadinstitute/picard#808]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
_Tool name(s), special parameters?_

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by yfarjoun** [comment]
I've been citing the github repository when needed. Not ideal, but at least
it's something.

**Comment by magicDGS** [comment]
If the Picard team agrees, they can Zenodo for creating a doi: https://guides.github.com/activities/citable-code/

It may be useful for this kind of situations...

**Comment by sooheelee** [comment]
That's a great idea! I can followup on creating such if the folks involved in the repo come to a consensus on this.

**Comment by sooheelee** [comment]
Looking closely at Zenodo, I see that this is aimed for researchers who want to capture exactly a repo at a certain state. I will distribute information about Zenodo instead.

**Comment by yfu** [comment]
Any updates on the dois of releases? Thanks!

**Comment by splaisan** [comment]
any update, we often wish to cite Picard and I have no better than the github so far!
Thanks

**Comment by rwanwork** [comment]
It seems the Picard tools' [(FAQ)](http://broadinstitute.github.io/picard/faq.html) currently suggests citing this link [http://broadinstitute.github.io/picard/](http://broadinstitute.github.io/picard/) and not GitHub.  Perhaps if there is a DOI later, the FAQ should also be updated as well?

**Comment by splaisan** [comment]
would you consider this bibtex entry valid for LateX (please correct if needed)?

```
@misc{Picard2018toolkit,
  author = {Broad Institute},
  title = {Picard toolkit},
  year = {2018},
  publisher = {Broad Institute},
  journal = {Broad Institute GitHub repository},
  howpublished = {\url{http://broadinstitute.github.io/picard/}}
}
```

**Comment by rwanwork** [comment]
I don't think there is a "rule" for how to cite software or a web page with LaTeX.  But many people have done it.  For example, this forum gives one answer, which is actually what I've been doing for many years:  [https://tex.stackexchange.com/questions/3587/how-can-i-use-bibtex-to-cite-a-web-page](https://tex.stackexchange.com/questions/3587/how-can-i-use-bibtex-to-cite-a-web-page).  That is, at a minimum:  title, howpublished, and note (indicating when you accessed that web page).

I believe you need to add an "author" since in BibTex, it is used as a sort key.

For software, I'd probably add the version.  I think for picard tools, you have to pick a tool and add "--version" to it:  picard BedToIntervalList --version .  In short, I am using this, **but** it doesn't mean you were wrong.  Maybe see this for a table about what can go in a @misc:  [https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#BibTeX](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#BibTeX)

@misc{Picard2018toolkit,
  author = {Broad Institute},
  title = {Picard Tools},
  howpublished = {\url{http://broadinstitute.github.io/picard/}},
  note = "Accessed:  2018-MM-DD; version X.Y.Z."
}

**Comment by splaisan** [comment]
Thanks @rwanwork !

For those who would like to reproduce and after some tries not showing some of your edits like notes..., here is what I got in RStudio

`Broad Institute. (Accessed: 2018/02/21; version 2.17.8). “Picard Tools.”Broad Institute, GitHub repository. http://broadinstitute.github.io/picard/.`

```
% PicardTools
@misc{Picard2018toolkit,
  author = {{ Broad Institute}},
  title = {Picard Tools},
  journal = {{ Broad Institute, GitHub repository}},
  Year={(Accessed: 2018/02/21; version 2.17.8)},
  howpublished = {\url{http://broadinstitute.github.io/picard/}}
}
```
I had to add a space missing after title but I am close now. double curled to keep text together
Best

**Comment by romunov** [comment]
Please consider adding some citation information to the main (man) page.
