### ISSUE TITLE
SortSam reduces file size by about 4 times!  Is this normal?

### ISSUE THREAD

**Issue by CodeInTheSkies** [broadinstitute/picard#871]
### Affected tool(s)
SortSam

### Affected version(s)
- [ ] version 2.6.0

### Description 
I used SortSam to sort aligned BAM files, aligned using Bowtie2.  Initially, the tool had some memory issues, but I eventually solved those by manually setting the tmp directory for java.  Now the program runs successfully.  But the output sorted BAM files are about 4 to 5 times smaller in size than the input BAMs.  Is this normal, or is there something else going on?

#### Steps to reproduce
java -Xmx2g -Djava.io.tmpdir=./tmp -jar /software/picard/2.6.0/picard.jar SortSam I=input.bam O=Sorted_output.bam SORT_ORDER=coordinate TMP_DIR=./tmp

**Comment by tfenne** [comment]
This is not totally unusual.  I'm not sure about 4-5 times, but going from a queryname sorted or unsorted BAM to a coordinate sorted BAM can reduce file size significantly.  This happens because it brings together reads that share similar sequences, and affords for better compression.  The effects are magnified for high coverage data (e.g. RNA seq, deep capture sequencing) where the number of similar reads is greater.  Similarly if the quality scores are quantized so they don't take up much room, then the reduction would be greater.

I would suggest running `samtools flagstat` and possibly also Picard's `CollectQualityYieldMetrics` on the input and output files if you are concerned and see if they yield the same results.

**Comment by CodeInTheSkies** [comment]
Thank you so much, Tim, for your very quick answer!  Really appreciate it!

OK, I will try `samtools flagstat` and `CollectQualityYieldMetrics`, as you suggested.
