### ISSUE TITLE
Why should I have a VCFHeader in there when I want to sort a VCF file?

### ISSUE THREAD

**Issue by seahurt** [broadinstitute/picard#916]
cmd:
java -jar picard.jar SortVcf  I:input.vcf O:sort.vcf  SEQUENCE_DICTIONARY=ref.fasta.dict
error:
Exception in thread "main" java.lang.IllegalStateException: Key AF found in VariantContext field INFO at 1:11169345 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.

Hey man , it is unresonable... I just want to sort the vcf by chr number, which has nothing to do with the AF tag in the content. Why should I have it? I have another tens of tags there without the header info. I guess I need to add those too.  But it is too hard...

**Comment by yfarjoun** [comment]
This comes from a library that Picard uses, HtsJdk. The VCF encoder (which it needs to write a new vcf...) requires that all fields are properly defined so that it is sure that the types are correct. It might be possible to ask that less strict validation of VCF be considered, but my personal advice for you would be to bite the bullet and add the VCF fields...it will protect you from silly mistakes later down the road.

**Comment by vdauwera** [comment]
FWIW a tool was added some months ago to make it easier to fix the VCF header when tags are missing. I forget the exact name but it's something like fix vcf header, iirc.

**Comment by yfarjoun** [comment]
can you point to it please?

**Comment by vdauwera** [comment]
LMGTFY... https://www.google.com/search?q=picard+fixvcfheader

It doesn't show up in the docs because whoever added it forgot to add it to the list of documentation targets. This will be fixed once we have the Barclay docs wired up correctly. (Work is planned for week after next)
