### ISSUE TITLE
Example Command For UmiAwareMarkDuplicatesWithMateCigar

### ISSUE THREAD

**Issue by gk7279** [broadinstitute/picard#953]
Hi-

Can you please provide an example command for UmiAwareMarkDuplicatesWithMateCigar to use with paired end RNSEQ?

Thanks

**Comment by yfarjoun** [comment]
UmiAwareMarkDuplicatesWithMateCigar will likely break with RNA seq as it
will need to hold too many reads in memory.

**Comment by fleharty** [comment]
@gk7279 
I've never tested UmiAwareMarkDuplicateWithMateCigar on RNAseq data, and I don't know if it would work.

@yfarjoun is correct, the way that UmiAwareMarkDuplicatesWithMateCigar works, it is likely that the tool would run out of memory with RNA because there can be very large distances between read pairs.   But maybe it is worth trying (though it will probably fail).

The usage is straightforward.  
java -jar $PICARD UmiAwareMarkDuplicatesWithMateCigar I=input.bam O=output.bam M=duplication.metrics UMI_METRICS=umi.metrics

where input.bam is the bam you wish to deduplicate.
output.bam is the bam you wish to create.
and duplication.metrics and umi.metrics are metrics files that will be created after the tool finishes.

**Comment by nh13** [comment]
@fleharty Does `UmiAwareMarkDuplicatesWithMateCigar` extend `MarkDuplicatesWithMateCigar`?  If so, the usage in the latter says it's not suited for data with large gaps, like RNA-Seq.  Likely the usage should be updated in the former if so.

**Comment by fleharty** [comment]
@nh13 Good point, I will update the usage to include a comment about `UmiAwareMarkDuplicatesWithMateCigar` not being well suited for data with large gaps.

**Comment by fleharty** [comment]
@nh13 
Actually, it extends `SimpleMarkDuplicatesWithMateCigar`.  I'm confused as to why it has this name rather than SimpleMarkDuplicates because it ultimately extends from `MarkDuplicates`.

Since it ultimately extends from `MarkDuplicates`, is it possible that this tool could be used on reads with large gaps like RNAseq?  Also, should this tool be renamed from 'UmiAwareMarkDuplicatesWithMateCigar' to 'UmiAwareMarkDuplicates' to avoid confusion?

**Comment by nh13** [comment]
All I know is that the algorithm used in `MarkDuplicatesWithMateCigar` attempts to limit memory consumption at the cost of not handling gaps well.

**Comment by yfarjoun** [comment]
The confusing thing is that both MarkDuplicatesWithMateCigar and SimpleMarckDuplicatesWithMateCigar use the MC tags to avoid having to find the mate before determining the duplicate status. They both need to read enough reads to be "sure" that they found all the reads that have 5' ends positioned at their current place on the reference. With RNA this can be many many reads. 

The difference between them is that SMDWMC uses a DuplicateSetIterator, while MDWMC does not (it does some fancy tricks that @nh13 is being very modest about...).

Since UmiAwareMarkDuplicatesWithMateCigar also uses the MC tag, I think that it qualifies as a *MDWMC and according to the naming it might have been preferable to call it UmiAware**Simple**MarkDuplicatesWithMateCigar, but I doubt that would make things better....

**Comment by fleharty** [comment]
Right, so because of this, I think it is appropriate to add a comment to the usage section that makes the user aware this tool isn't appropriate for RNAseq, or other data that has large alignment gaps.

**Comment by fleharty** [comment]
This issue was resolved by adding a usage comment in pull request,
https://github.com/broadinstitute/picard/pull/959
